name: Todo CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml -Dspring.datasource.url=jdbc:postgresql://${{DB_HOST}}:5432/todo -Dspring.datasource.username=${{DB_USER}} -Dspring.datasource.password=${{DB_PASS}} -Dapi.security.token.secret=${{JWT_SECRET}}
