name: Todo CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    environment: gcp-prod
    steps:
      - uses: actions/checkout@v3
        env:
          SUPER_SECRET: fasn
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml -Dspring.datasource.url=jdbc:postgresql://${{format('{0}',  secrets.DB_HOST)}}/todo -Dspring.datasource.username=${{format('{0}',  secrets.DB_USER )}} -Dspring.datasource.password=${{format('{0}',  secrets.DB_PASS )}} ${{format('-Dapi.security.token.secret={0}',  secrets.JWT_SECRET )}}

      - name: Build & push Docket image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: dougss10/todo
          tags: latest
          registry: docker.io
          dockerfile: DockerFile
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASS }}
